### ISSUE TITLE
Version 12.0.0 doesn't work with testrpc.

### ISSUE THREAD

**Issue by alcuadrado** [MetaMask/provider-engine#134]
I'm not sure if this should be reported here or in testrpc, but version 12.0.0 isn't working with testrpc. 

I'm getting a "Couldn't find block by reference: 0x01" error when [running this reproduction script](https://github.com/alcuadrado/web3-provider-engine-bug-repro/blob/master/index.js).

This works with v11.0.0, with exactly the same script. [Here](https://github.com/alcuadrado/web3-provider-engine-bug-repro/tree/working-version) is a working version of it. Note that only its `package.json` and `yarn.lock` change.

Here's the complete stacktrace of the error:
```
ethquery failure { method: 'eth_getBlockByNumber', params: [ '0x01', false ] } Error: Error: Couldn't find block by reference: 0x01
    at BlockchainDouble.getBlock (/usr/local/lib/node_modules/ethereumjs-testrpc/lib/blockchain_double.js:130:21)
    at GethApiDouble.eth_getBlockByNumber (/usr/local/lib/node_modules/ethereumjs-testrpc/lib/subproviders/geth_api_double.js:119:25)
    at GethApiDouble.handleRequest (/usr/local/lib/node_modules/ethereumjs-testrpc/lib/subproviders/geth_api_double.js:61:10)
    at next (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/index.js:95:18)
    at SolcSubprovider.handleRequest (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/subproviders/solc.js:28:7)
    at next (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/index.js:95:18)
    at VmSubprovider.handleRequest (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/subproviders/vm.js:40:12)
    at next (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/index.js:95:18)
    at GethDefaults.handleRequest (/usr/local/lib/node_modules/ethereumjs-testrpc/lib/subproviders/gethdefaults.js:17:12)
    at next (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/index.js:95:18)
    at /Users/pato/ether/bug/node_modules/web3-provider-engine/subproviders/web3.js:15:44
    at exports.XMLHttpRequest.request.onreadystatechange (/Users/pato/ether/bug/node_modules/web3/lib/web3/httpprovider.js:114:13)
    at exports.XMLHttpRequest.dispatchEvent (/Users/pato/ether/bug/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at setState (/Users/pato/ether/bug/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
    at IncomingMessage.<anonymous> (/Users/pato/ether/bug/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

Error: Error: Couldn't find block by reference: 0x01
    at BlockchainDouble.getBlock (/usr/local/lib/node_modules/ethereumjs-testrpc/lib/blockchain_double.js:130:21)
    at GethApiDouble.eth_getBlockByNumber (/usr/local/lib/node_modules/ethereumjs-testrpc/lib/subproviders/geth_api_double.js:119:25)
    at GethApiDouble.handleRequest (/usr/local/lib/node_modules/ethereumjs-testrpc/lib/subproviders/geth_api_double.js:61:10)
    at next (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/index.js:95:18)
    at SolcSubprovider.handleRequest (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/subproviders/solc.js:28:7)
    at next (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/index.js:95:18)
    at VmSubprovider.handleRequest (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/subproviders/vm.js:40:12)
    at next (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/index.js:95:18)
    at GethDefaults.handleRequest (/usr/local/lib/node_modules/ethereumjs-testrpc/lib/subproviders/gethdefaults.js:17:12)
    at next (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/index.js:95:18)
    at /Users/pato/ether/bug/node_modules/web3-provider-engine/subproviders/web3.js:15:44
    at exports.XMLHttpRequest.request.onreadystatechange (/Users/pato/ether/bug/node_modules/web3/lib/web3/httpprovider.js:114:13)
    at exports.XMLHttpRequest.dispatchEvent (/Users/pato/ether/bug/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at setState (/Users/pato/ether/bug/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
    at IncomingMessage.<anonymous> (/Users/pato/ether/bug/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by flyswatter** [comment]
We're aware of this issue, although it does belong here too.

I've opened an issue to fix it on `eth-block-tracker`, which is where we would fix this for provider-engine:
https://github.com/kumavis/eth-block-tracker/issues/2

I've also fixed it on testrpc, waiting for a merge:
https://github.com/ethereumjs/testrpc/pull/295

**Comment by flyswatter** [comment]
I've added a fix PR for `eth-block-tracker` too, but need @kumavis back to merge it.  He's out for a bit, so please just roll back your provider-engine for the time being and work with that.

https://github.com/kumavis/eth-block-tracker/pull/3

**Comment by alcuadrado** [comment]
Thanks for the quick answer @flyswatter! I was sure that this couldn't be unreported, but wasn't sure where to look for the issue.

I'm downgrading provider-engine for now then. Thanks!
