### ISSUE TITLE
Error: Cannot find module 'eth-block-tracker'

### ISSUE THREAD

**Issue by OR13** [MetaMask/provider-engine#164]
hello : ) I have some integration tests which just started failing.

```
Error: Cannot find module 'eth-block-tracker'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/orie/TransmuteIndustries/transmute-framework/node_modules/web3-provider-engine/index.js:4:25)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

https://travis-ci.org/transmute-industries/transmute-framework/builds/242685558

I can see previous builds that succeeded had:

```
├─┬ @digix/truffle-lightwallet-provider@0.0.12 
│ ├─┬ eth-lightwallet@2.5.4 
│ │ ├── bignumber.js@2.0.7 
│ │ ├─┬ bitcore-lib@0.14.0 
│ │ │ ├── bn.js@2.0.4 
│ │ │ ├── bs58@2.0.0 
│ │ │ ├── buffer-compare@1.0.0 
│ │ │ ├─┬ elliptic@3.0.3 
│ │ │ │ ├── brorand@1.0.5 
│ │ │ │ └── hash.js@1.0.3 
│ │ │ ├── inherits@2.0.1 
│ │ │ └── lodash@3.10.1 
│ │ ├── bitcore-mnemonic@1.2.5 
│ │ ├─┬ buffer@4.9.1 
│ │ │ ├── base64-js@1.2.0 
│ │ │ ├── ieee754@1.1.8 
│ │ │ └── isarray@1.0.0 
│ │ ├─┬ elliptic@3.1.0 
│ │ │ ├── bn.js@2.2.0 
│ │ │ ├── brorand@1.1.0 
│ │ │ └── hash.js@1.0.3 
│ │ ├── scrypt-async@1.3.1 
│ │ ├── tweetnacl@0.13.2 
│ │ └─┬ web3@0.15.3 
│ │   └── bignumber.js@2.0.7  
│ ├─┬ ethereumjs-tx@1.3.1 
│ │ └── ethereum-common@0.0.18 
│ └─┬ web3-provider-engine@12.2.2 
```

And the current one that is failing is:

```
├─┬ @digix/truffle-lightwallet-provider@0.0.12 
│ ├─┬ eth-lightwallet@2.5.4 
│ │ ├── bignumber.js@2.0.7  
│ │ ├─┬ bitcore-lib@0.14.0 
│ │ │ ├── bn.js@2.0.4 
│ │ │ ├── bs58@2.0.0 
│ │ │ ├── buffer-compare@1.0.0 
│ │ │ ├─┬ elliptic@3.0.3 
│ │ │ │ ├── brorand@1.0.5 
│ │ │ │ └── hash.js@1.0.3 
│ │ │ ├── inherits@2.0.1 
│ │ │ └── lodash@3.10.1 
│ │ ├── bitcore-mnemonic@1.2.5 
│ │ ├─┬ buffer@4.9.1 
│ │ │ ├── base64-js@1.2.0 
│ │ │ └── ieee754@1.1.8 
│ │ ├─┬ elliptic@3.1.0 
│ │ │ ├── bn.js@2.2.0 
│ │ │ ├── brorand@1.1.0 
│ │ │ └── hash.js@1.0.3 
│ │ ├── scrypt-async@1.3.1 
│ │ ├── tweetnacl@0.13.2 
│ │ └─┬ web3@0.15.3 
│ │   └── bignumber.js@2.0.7  
│ ├─┬ ethereumjs-tx@1.3.1 
│ │ └── ethereum-common@0.0.18 
│ └─┬ web3-provider-engine@12.2.4 
```

It looks to me like web3-provider-engine@12.2.4 is the culprit.

It should be reproducible by installing "digix/truffle-lightwallet-provider": "0.0.12"

and running truffle migrate with truffle.js looking something like this:

```
const LightWalletProvider = require('@digix/truffle-lightwallet-provider')

module.exports = {
  networks: {
    "development": {
      host: "localhost",
      port: 8545,
      network_id: "*",
    },
    "ropsten": {
      provider: new LightWalletProvider({
        keystore: './sigmate-v3-ti.json',
        password: global.lightWalletPassword,
        rpcUrl: 'https://ropsten.infura.io',
        debug: true,
        pollingInterval: 2000 
      }),
      network_id: '*',
    },
  }
};
```

I believe digix/truffle-lightwallet-provider
is loading web3-provider-engine@12.2.4
and causing my build to fail >:(

Is there anything I can do to resolve this?

**Comment by OR13** [comment]
I was able to temporarily resolve this issue by commenting out the digix/truffle-lightwallet-provider reference in truffle.js.

**Comment by flyswatter** [comment]
You should be able to fix this by running a fresh `npm install`.

**Comment by OR13** [comment]
Thanks for the quick reply :)

I deleted node_modules and ran `npm install`

Still seeing same error.

**Comment by hitchcott** [comment]
hi @OR13 

I've just republished lightwallet-provider with fixed dependancy versions, so it should install the specific version I tested with (12.0.2). Please try installing the provider @ v 0.0.13.

**Comment by eolszewski** [comment]
Thanks, @hitchcott!

**Comment by flyswatter** [comment]
Was fixed on `eth-block-tracker` this morning:
https://github.com/MetaMask/eth-block-tracker/issues/22

**Comment by OR13** [comment]
Thanks @hitchcott @flyswatter!
