### ISSUE TITLE
Web3ProviderEngine does not support synchronous requests.

### ISSUE THREAD

**Issue by OR13** [MetaMask/provider-engine#178]
It is possible this is the result of jest / babel / typescript, in which case, sorry :(

```
"web3": "1.0.0-beta.18",
"web3-provider-engine": "13.2.9"
```

```
this.engine = new ProviderEngine()
this.engine.addProvider(new RpcSubprovider({rpcUrl: this.providerUrl}) )
this.web3 = new Web3(this.engine) // does not work
this.web3 = new Web3(new Web3.providers.HttpProvider(providerUrl)); // works
```

```
Web3ProviderEngine does not support synchronous requests.

at Web3ProviderEngine.Object.<anonymous>.Web3ProviderEngine.send (node_modules/web3-provider-engine/index.js:71:9)
at RequestManager.Object.<anonymous>.RequestManager.send (node_modules/web3/packages/web3-eth/node_modules/web3-core/node_modules/web3-core-requestmanager/src/index.js:129:19)
at sendRequest (node_modules/web3/packages/web3-eth/node_modules/web3-core-method/src/index.js:525:42)
at Eth.send [as getAccounts] (node_modules/web3/packages/web3-eth/node_modules/web3-core-method/src/index.js:540:13)
at src/MetaCoinAPI/MetaCoinAPI.spec.ts:23:47
at step (src/MetaCoinAPI/MetaCoinAPI.spec.ts:1:44)
at Object.next (src/MetaCoinAPI/MetaCoinAPI.spec.ts:1:44)
at src/MetaCoinAPI/MetaCoinAPI.spec.ts:1:44
at Promise (<anonymous>)
at Object.<anonymous>.__awaiter (src/MetaCoinAPI/MetaCoinAPI.spec.ts:1:44)
at Object.<anonymous> (src/MetaCoinAPI/MetaCoinAPI.spec.ts:21:61)
at Promise (<anonymous>)
at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:188:7)
```

The call that fails is:

https://github.com/transmute-industries/typescript-truffle-lib/blob/master/src/MetaCoinAPI/MetaCoinAPI.spec.ts#L23

**Comment by flyswatter** [comment]
Web3 does not return promises, so your line `let accounts = await metaCoinAPI.web3.eth.getAccounts()` does not actually await anything, and instead calls the `getAccounts()` method without a callback, which is considered synchronous, and disallowed, throwing that error. You should either pass it a callback, promisify that function, or use a promise-returning abstraction like [ethjs](https://github.com/ethjs/ethjs) or [web3 1.0](https://web3js.readthedocs.io/en/1.0/).

**Comment by OR13** [comment]
@flyswatter thanks. sorry, that was sloppy on my part. I've been testing variations and linked you to one that was obviously wrong.

I see the same error with:

```
metaCoinAPI.web3.eth.getAccounts((error: any, result: any) =>{
  console.log(result)
})
```

https://travis-ci.org/transmute-industries/typescript-truffle-lib/builds/271848542

Seems like it thinks everything is synchronous even when i pass a callback like about.

This might have something to do with the trickery I'm forced to use to get jest to work.

**Comment by OR13** [comment]
This seems to have been caused by a combination of using the web3 1.0 beta (using stable 0.20.0 now) and forgetting to `engine.start()`

**Comment by abhinav2196** [comment]
It was causing trouble for me while using 0.20 version of web3.
Updating it to web3(v1.0) it works, but I am unable to getaccounts. They return null []
