### ISSUE TITLE
GaspriceSubprovider gives error Cannot read property 'transactions'

### ISSUE THREAD

**Issue by izetex** [MetaMask/provider-engine#211]
I am using GaspriceSubprovider with Infura RPC and Ropsten network:

```javascript
const engine = new ProviderEngine();
engine.addProvider(new GaspriceSubprovider());
engine.addProvider(new WalletSubprovider(wallet, {}));
engine.addProvider(new Web3Subprovider(new Web3.providers.HttpProvider(config.ethereum.ropsten.url,
                            config.ethereum.timeout )));

engine.start();
web3 = new Web3(engine);

var result = web3.eth.getGasPrice(function(e,r){
    console.log(web3.fromWei(r).toNumber());
});
```

It gives an error when invoking getGasPrice() 
```
TypeError: Cannot read property 'transactions' of null
   at /Users/studnev/dev4bc/provider-engine/subproviders/gasprice.js:45:30
    at /Users/studnev/dev4bc/provider-engine/index.js:149:9
    at /Users/studnev/dev4bc/provider-engine/node_modules/async/internal/once.js:12:16
    at replenish (/Users/studnev/dev4bc/provider-engine/node_modules/async/internal/eachOfLimit.js:59:25)
    at iterateeCallback (/Users/studnev/dev4bc/provider-engine/node_modules/async/internal/eachOfLimit.js:49:17)
    at /Users/studnev/dev4bc/provider-engine/node_modules/async/internal/onlyOnce.js:12:16
    at resultObj.id (/Users/studnev/dev4bc/provider-engine/index.js:129:9)
```

I suspect the problem is in the way how blocks are queried. When i fixed the code by moving te query block window backwards, the error gone:

```javascript
+++ subproviders/gasprice.js	(revision )
@@ -28,7 +28,7 @@ 
   self.emitPayload({ method: 'eth_blockNumber' }, function(err, res) {
     // FIXME: convert number using a bignum library
-    var lastBlock = parseInt(res.result, 16)
+    var lastBlock = parseInt(res.result, 16) - 10
```

I can submit PR for this if it is a bug

**Comment by kumavis** [comment]
I dont use or maintain this subprovider : (
Added a more specific error for when the `res.result` is missing
and cherry picked your `delayInBlocks` fix
