### ISSUE TITLE
Error getting the nonce local testrpc when there's a revert

### ISSUE THREAD

**Issue by anxolin** [MetaMask/provider-engine#300]
The nonce calculation fails in a local testrpc after you revert the state to a prior one.

The error:
```
    Error: the tx doesn't have the correct nonce. account has nonce of: 18 tx has nonce of: 19
        at /Users/anxo/code/gnosis/dx-services/node_modules/web3-provider-engine/subproviders/provider.js:19:36
        at XMLHttpRequest.request.onreadystatechange (/Users/anxo/code/gnosis/dx-services/node_modules/truffle-hdwallet-provider/node_modules/web3/lib/web3/httpprovider.js:118:13)
        at XMLHttpRequest.Object.<anonymous>.XMLHttpRequestEventTarget.dispatchEvent (/Users/anxo/code/gnosis/dx-services/node_modules/xhr2/lib/xhr2.js:64:18)
        at XMLHttpRequest.Object.<anonymous>.XMLHttpRequest._setReadyState (/Users/anxo/code/gnosis/dx-services/node_modules/xhr2/lib/xhr2.js:354:12)
        at XMLHttpRequest.Object.<anonymous>.XMLHttpRequest._onHttpResponseEnd (/Users/anxo/code/gnosis/dx-services/node_modules/xhr2/lib/xhr2.js:509:12)
        at IncomingMessage.<anonymous> (/Users/anxo/code/gnosis/dx-services/node_modules/xhr2/lib/xhr2.js:469:24)
        at IncomingMessage.emit (events.js:187:15)
        at IncomingMessage.EventEmitter.emit (domain.js:441:20)
        at endReadableNT (_stream_readable.js:1094:12)
        at process._tickCallback (internal/process/next_tick.js:63:19)
```

I believe the issue is because the `NonceTrackerSubprovider` is caching the nonce even after reverting the state of a the local ganache.

Reverting the state in a local testrpc is very common thing to do in order to make the test repeatable, and to avoid tests influence each other.

Clearing the cache, make sure, we get the new nonce from the new state of the blockchain.

**Comment by kiliw** [comment]
The cache is also not updated when a transaction simply fails. I assume the "sendRawTransaction" method is never called and as such the cached nonce is not increased. However ganache increases the nonce for the account trying to send the reverted (failed) transaction. I had a look at the code to see whether I could force some kind of update but I did not see a chance. Is there no way to just manually increase the nonce?

**Comment by kiliw** [comment]
Issue should be reopened: Make sure that **whenever** ganache increases the nonce, the cached nonce is also increased.
